trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo systemctl start mysql

    sudo mysqladmin -u root password 'root'

    mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS snowman;"
    mysql -uroot -proot -e "CREATE USER IF NOT EXISTS 'username'@'localhost' IDENTIFIED BY 'password';"
    mysql -uroot -proot -e "ALTER USER 'username'@'localhost' IDENTIFIED BY 'password';"
    mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON snowman.* TO 'username'@'localhost';"
    mysql -uroot -proot -e "FLUSH PRIVILEGES;"

    mysql -uusername -ppassword -e "SHOW DATABASES;"
  displayName: 'Setup MySQL'

- task: Maven@3
  displayName: 'Maven Build and Test'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'