trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y mysql-server

    sudo systemctl start mysql
    sudo systemctl status mysql --no-pager

    sudo mysql -e "CREATE DATABASE IF NOT EXISTS snowman;"
    sudo mysql -e "CREATE USER IF NOT EXISTS 'username'@'localhost' IDENTIFIED BY 'password';"
    sudo mysql -e "GRANT ALL PRIVILEGES ON snowman.* TO 'username'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"
  displayName: 'Setup MySQL'

- task: Maven@3
  displayName: 'Maven Build and Test'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'